all:	ex1 ex2 ex3

ex1:	ex1.c
	@cc -o ex1 ex1.c -lpthread

ex2:	ex2.c
	@cc -o ex2 ex2.c -lpthread

ex3:	ex3.c
	@cc -o ex3 ex3.c -lpthread

clean:
	@rm -f ex1 ex2 ex3 *~

info:
	@echo "(C) Roland Teodorowitsch (17 set. 2013)"

